const PAGE_SIZE = 3;
const MAX_LOADED_PAGES = 7;
const ROW_HEIGHT = 166;
const PAGE_HEIGHT = PAGE_SIZE * ROW_HEIGHT;
const SCROLL_DELAY = 100;

export {
    PAGE_SIZE,
    MAX_LOADED_PAGES,
    ROW_HEIGHT,
    PAGE_HEIGHT,
    SCROLL_DELAY
};
